# Generated by Django 5.1.5 on 2025-04-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UfrainRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dob', models.DateField()),
                ('phone_no', models.CharField(max_length=15)),
                ('hight', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
